# This is a basic workflow to help you get started with Actions

name: Trips CICD

env:
  registry: docker.pkg.github.com
  repository: hattan/openhack-devops-team-gh/api-trips
  docker_path: apis/trips
  staging_url: https://openhackxv61mxh2trips-staging.azurewebsites.net/
  prod_url: https://openhackxv61mxh2trips.azurewebsites.net/
  resource_group: openhackxv61mxh2rgweb
  app_name: openhackxv61mxh2trips
  build_name: Trips
  webv_path: apis/trips/webvalidate

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths: 
      -apis/trips/**  
      -.github/workflows/trips.yml
  pull_request:
    branches: [ master ]
    paths: 
      -apis/trips/**  
      -.github/workflows/trips.yml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
        with:
          go-version: 1.12

      - name: Install dependencies
        run: go get

      # Runs a set of commands using the runners shell
      - name: Run Unit Tests
        run: go test ./tests
